### ISSUE TITLE
No longer builds

### ISSUE THREAD

**Issue by rboarman** [glawson6/mule-starter-app#1]
Your project looks great. However, it appears to be out of date and no longer builds. I'm new to Mule and my Maven skills are still progressing. Is there any way I could please ask you to update your project so that it works? Thank you!

**Comment by glawson6** [comment]
Ok. I will take a look.

**Comment by glawson6** [comment]
The maven part looks like it is still working. I will check the gradle portion. 

```
On Wednesday, November 18, 2015 5:40 PM, Rick Boarman <notifications@github.com> wrote:
```

 Your project looks great. However, it appears to be out of date and no longer builds. I'm new to Mule and my Maven skills are still progressing. Is there any way I could please ask you to update your project so that it works? Thank you!—

**Comment by glawson6** [comment]
Are you running the maven build or the gradle build?

**Comment by rboarman** [comment]
Thank you for looking at this. Yes, I am using maven. The first issue was that I needed to change the tools version from 1.0 to 1.1.

< mule.tools.version >1.1< /mule.tools.version >

Once I did that, I started to get a bunch of other dependency errors.

[ERROR] Failed to execute goal on project mule-starter-app: Could not resolve dependencies for project org.taptech.app:mule-starter-app:jar:1.0-SNAPSHOT: Could not find artifact org.mule:mule-extensions-api:jar:1.0.0-SNAPSHOT

**Comment by glawson6** [comment]
Are you running this command line or from an IDE? 

```
On Wednesday, November 18, 2015 6:48 PM, Rick Boarman <notifications@github.com> wrote:
```

 Thank you for looking at this. Yes, I am using maven. The first issue was that I needed to change the tools version from 1.0 to 1.1.1.1Once I did that, I started to get a bunch of other dependency errors.[ERROR] Failed to execute goal on project mule-starter-app: Could not resolve dependencies for project org.taptech.app:mule-starter-app:jar:1.0-SNAPSHOT: Could not find artifact org.mule:mule-extensions-api:jar:1.0.0-SNAPSHOT —

**Comment by rboarman** [comment]
I tried both, same errors

**Comment by glawson6** [comment]
Can you post the entire error log from when you run the mvn command? 

```
On Wednesday, November 18, 2015 7:12 PM, Rick Boarman <notifications@github.com> wrote:
```

 I tried both, same errors—

**Comment by rboarman** [comment]
[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building Mule mule-starter-app Application 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] Downloading: http://nexwebp01.us.tycoelectronics.com/nexus/content/groups/public-snapshots/org/mule/mule-extensions-api/1.0.0-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://nexwebp01.us.tycoelectronics.com/nexus/content/groups/public-snapshots/org/mule/mule-extensions-api/1.0.0-SNAPSHOT/mule-extensions-api-1.0.0-SNAPSHOT.pom
[WARNING] The POM for org.mule:mule-extensions-api:jar:1.0.0-SNAPSHOT is missing, no dependency information available
[INFO] Downloading: http://nexwebp01.us.tycoelectronics.com/nexus/content/groups/public-snapshots/org/mule/mule-extensions-api/1.0.0-SNAPSHOT/mule-extensions-api-1.0.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.840 s
[INFO] Finished at: 2015-11-18T16:39:14-05:00
[INFO] Final Memory: 22M/218M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project mule-starter-app: Could not resolve dependencies for project org.taptech.app:mule-starter-app:jar:1.0-SNAPSHOT: Could not find artifact org.mule:mule-extensions-api:jar:1.0.0-SNAPSHOT in nexus-snapshots (http://nexwebp01.us.tycoelectronics.com/nexus/content/groups/public-snapshots) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

nexwebp01.us.tycoelectronics.com is our internal repo. I had to copy the files locally into the my m2_repo directory.

Files in the local repo:

C:\m2_repo\org\mule\mule-extensions-api\1.0.0-SNAPSHOT
11/18/2015  04:18 PM             1,004 maven-metadata.xml
11/18/2015  04:20 PM            59,945 mule-extensions-api-1.0.0-20151118.180409-29.jar
11/18/2015  04:20 PM             9,988 mule-extensions-api-1.0.0-20151118.180409-29.pom
11/18/2015  04:39 PM               505 mule-extensions-api-1.0.0-SNAPSHOT.jar.lastUpdated
11/18/2015  04:39 PM               505 mule-extensions-api-1.0.0-SNAPSHOT.pom.lastUpdated
11/18/2015  04:39 PM               325 resolver-status.properties

**Comment by glawson6** [comment]
Do you have a settings file? Are you running on a corporate network? 

```
On Wednesday, November 18, 2015 7:31 PM, Rick Boarman <notifications@github.com> wrote:
```

 [INFO] Scanning for projects...
[INFO]

[INFO] ------------------------------------------------------------------------
[INFO] Building Mule mule-starter-app Application 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] Downloading: http://nexwebp01.us.tycoelectronics.com/nexus/content/groups/public-snapshots/org/mule/mule-extensions-api/1.0.0-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://nexwebp01.us.tycoelectronics.com/nexus/content/groups/public-snapshots/org/mule/mule-extensions-api/1.0.0-SNAPSHOT/mule-extensions-api-1.0.0-SNAPSHOT.pom
[WARNING] The POM for org.mule:mule-extensions-api:jar:1.0.0-SNAPSHOT is missing, no dependency information available
[INFO] Downloading: http://nexwebp01.us.tycoelectronics.com/nexus/content/groups/public-snapshots/org/mule/mule-extensions-api/1.0.0-SNAPSHOT/mule-extensions-api-1.0.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.840 s
[INFO] Finished at: 2015-11-18T16:39:14-05:00
[INFO] Final Memory: 22M/218M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project mule-starter-app: Could not resolve dependencies for project org.taptech.app:mule-starter-app:jar:1.0-SNAPSHOT: Could not find artifact org.mule:mule-extensions-api:jar:1.0.0-SNAPSHOT in nexus-snapshots (http://nexwebp01.us.tycoelectronics.com/nexus/content/groups/public-snapshots) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionExceptionnexwebp01.us.tycoelectronics.com is our internal repo. I had to copy the files locally into the my m2_repo directory.Files in the repo:C:\m2_repo\org\mule\mule-extensions-api\1.0.0-SNAPSHOT
11/18/2015 04:18 PM 1,004 maven-metadata.xml
11/18/2015 04:20 PM 59,945 mule-extensions-api-1.0.0-20151118.180409-29.jar
11/18/2015 04:20 PM 9,988 mule-extensions-api-1.0.0-20151118.180409-29.pom
11/18/2015 04:39 PM 505 mule-extensions-api-1.0.0-SNAPSHOT.jar.lastUpdated
11/18/2015 04:39 PM 505 mule-extensions-api-1.0.0-SNAPSHOT.pom.lastUpdated
11/18/2015 04:39 PM 325 resolver-status.properties—

**Comment by rboarman** [comment]
Yes to both. I am on a corporate network with a proxy and yes I have a settings file (attached).

[settings.xml.txt](https://github.com/glawson6/mule-starter-app/files/38477/settings.xml.txt)

**Comment by glawson6** [comment]
rename your settings.xml to settings.xml.bkup. Then run it. Your proxy servers are not allowing the jars to get downloaded. 

```
On Wednesday, November 18, 2015 7:45 PM, Rick Boarman <notifications@github.com> wrote:
```

 Yes to both. I am on a corporate network with a proxy and yes I have a settings file (attached).settings.xml.txt—

**Comment by rboarman** [comment]
It looks to me like the firewall is blocking me now:

[INFO] Scanning for projects...
[INFO] Downloading: http://repository.codehaus.org/org/codehaus/org/springframework/boot/spring-boot-starter-parent/1.2.3.RELEASE/spring-boot-starter-parent-1.2.3.RELEASE.pom
[INFO] Downloading: http://maven.wso2.org/nexus/content/groups/wso2-public/org/springframework/boot/spring-boot-starter-parent/1.2.3.RELEASE/spring-boot-starter-parent-1.2.3.RELEASE.pom
[INFO] Downloading: https://repository-master.mulesoft.org/releases/org/springframework/boot/spring-boot-starter-parent/1.2.3.RELEASE/spring-boot-starter-parent-1.2.3.RELEASE.pom
[INFO] Downloading: https://repository-master.mulesoft.org/snapshots/org/springframework/boot/spring-boot-starter-parent/1.2.3.RELEASE/spring-boot-starter-parent-1.2.3.RELEASE.pom
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-parent/1.2.3.RELEASE/spring-boot-starter-parent-1.2.3.RELEASE.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.taptech.app:mule-starter-app:1.0-SNAPSHOT: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:1.2.3.RELEASE from/to codehaus (http://repository.codehaus.org/org/codehaus): repository.codehaus.org and 'parent.relativePath' points at wrong local POM @ line 4, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]  
[ERROR]   The project org.taptech.app:mule-starter-app:1.0-SNAPSHOT (C:\Users\te210709\Documents\Eclipse\workspace\mule-starter-app\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.taptech.app:mule-starter-app:1.0-SNAPSHOT: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:1.2.3.RELEASE from/to codehaus (http://repository.codehaus.org/org/codehaus): repository.codehaus.org and 'parent.relativePath' points at wrong local POM @ line 4, column 13: Unknown host repository.codehaus.org -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

This is why I manually copied the files into my local repo.

**Comment by glawson6** [comment]
You have environment issues. I am closing this issue.
